### ISSUE TITLE
Cannot launch server with MohistMC

### ISSUE THREAD

**Issue by Sphyix** [stal111/Valhelsia-Structures#73]
I tried to launch Enigmatica 6 ver. 0.1.14 with MohistMC (mohist is to implement bukkit/spigot API)
Server wasn't starting and I was getting some mixin errors.
I isolated the mods Valhelsia Structures and Valhelsia Core from the rest of the pack.

I noticed that it tries to load client-side stuff, not sure if that's the cause of the crash:

[16:55:25 WARN]: Error loading class: net/minecraft/client/renderer/entity/layers/CapeLayer (java.lang.ClassNotFoundException: null)
[16:55:25 WARN]: @Mixin target net.minecraft.client.renderer.entity.layers.CapeLayer was not found valhelsia_core.mixins.json:client.CapeLayerMixin
[16:55:26 FATAL]: Attempted to load class net/minecraft/client/renderer/BlockModelRenderer for invalid dist DEDICATED_SERVER
[16:55:26 WARN]: Error loading class: net/minecraft/client/renderer/BlockModelRenderer (java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/BlockModelRenderer for invalid dist DEDICATED_SERVER)
[16:55:26 WARN]: @Mixin target net.minecraft.client.renderer.BlockModelRenderer was not found valhelsia_structures.mixins.json:BlockModelRendererMixin

Then it crashes, full log file
[latest.log](https://github.com/ValhelsiaTeam/Valhelsia-Structures/files/6528333/latest.log)

How to reproduce:
MohistMC version: 1.16.5 #589
Valhelsia Core version: 16.0.8
Valhelsia Structures version: 1.16.5-0.1.1

Install MohistMC following their guide on wiki (https://wiki.mohistmc.com/#/install/windows)
Finish launching server following messages on the cmd
Close server, move Valhelsia Core and Valhelsia Structures into mods folder
Launch server again

**Comment by Vaelzan** [comment]
This should be fixed by this change in the code, which will be available on CurseForge when we have finished with the remaining changes for the next update. https://github.com/ValhelsiaTeam/Valhelsia-Structures/commit/13d1e272cef8dd4129581f6de2964958f1b376da

**Comment by mattiTD** [comment]
> This should be fixed by this change in the code, which will be available on CurseForge when we have finished with the remaining changes for the next update. [13d1e27](https://github.com/ValhelsiaTeam/Valhelsia-Structures/commit/13d1e272cef8dd4129581f6de2964958f1b376da)

@Vaelzan 
with this build the mohistMC still not working

MohistMC: 1.16.5-621
Valhelsia Core: 16.0.9
Valhelsia Structures: 1.16.5-0.1.2

[12:53:33 INFO]: [java.lang.Throwable:printStackTrace:-1]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method valhelsia_placeDousedTorch(Lnet/minecraft/entity/player/PlayerEntity;Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/math/BlockRayTraceResult;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V in valhelsia_structures.mixins.json:BucketItemMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap valhelsia_structures.refmap.json

[latest mohist log (2).txt](https://github.com/ValhelsiaTeam/Valhelsia-Structures/files/6602443/latest.mohist.log.2.txt)

**Comment by ghost** [comment]
> > This should be fixed by this change in the code, which will be available on CurseForge when we have finished with the remaining changes for the next update. [13d1e27](https://github.com/ValhelsiaTeam/Valhelsia-Structures/commit/13d1e272cef8dd4129581f6de2964958f1b376da)
> 
> @Vaelzan
> with this build the mohistMC still not working
> 
> MohistMC: 1.16.5-621
> Valhelsia Core: 16.0.9
> Valhelsia Structures: 1.16.5-0.1.2
> 
> [12:53:33 INFO]: [java.lang.Throwable:printStackTrace:-1]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method valhelsia_placeDousedTorch(Lnet/minecraft/entity/player/PlayerEntity;Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/math/BlockRayTraceResult;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V in valhelsia_structures.mixins.json:BucketItemMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap valhelsia_structures.refmap.json
> 
> [latest mohist log (2).txt](https://github.com/ValhelsiaTeam/Valhelsia-Structures/files/6602443/latest.mohist.log.2.txt)

I'm also attempting to run with the newest version of Valhelsia Structures (0.1.2). I encounter the same error as mattiTD on launch.

**Comment by TheMilkMansDad** [comment]
I too am also having the same issue when launching a Mohist server with Valhelsia Structures (0.1.2).

**Comment by PiciuU** [comment]
Same problem, Mohist doesnt work with https://www.curseforge.com/minecraft/modpacks/better-minecraft-otv-edition pack due to issue with Valhelsia Structures 0.1.1 and 0.1.2

**Comment by ACrazyD** [comment]
can confirm issue still present in 0.1.2

[14:50:44] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method valhelsia_placeDousedTorch(Lnet/minecraft/entity/player/PlayerEntity;Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/math/BlockRayTraceResult;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V in valhelsia_structures.mixins.json:BucketItemMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap valhelsia_structures.refmap.json

**Comment by Vaelzan** [comment]
The most recent reports are a different issue, albeit still involving Mohist (you can see that the logs are quite different). The 0.1.2 patch fixed the OP's issue (rendering code being incorrectly ran on Mohist servers), but revealed another issue when using Mohist. We're looking into it and will attempt to have it resolved in the upcoming minor release.
